---
apiVersion: v1
kind: Service
metadata:
  name: vault
  labels:
    app: vault
spec:
  ports:
    - port: 8200
      name: vault
      protocol: TCP
      targetPort: 8200
  selector:
    app: vault
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vault
spec:
  serviceName: vault
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
      - name: vault
        image: vault:1.4.3
        ports:
        - containerPort: 8200
          name: web
        volumeMounts:
        - name: vault-config
          mountPath: /etc/vault
        - name: vault-data
          mountPath: /lib/vault
      volumes:
      - name: config-vault
        configMap:
          name: vault
          items:
            - key: vault.hcl
              path: vault.hcl
  volumeClaimTemplates:
  - metadata:
      name: vault-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 500Mi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault
data:
  vault.hcl: |
    listener "tcp" {
      address     = "0.0.0.0:8200"
      tls_disabled = 1
    }

    api_addr = "http://vault:8200"

    storage "file" {
      path = "/lib/vault"
    }

    telemetry {
      prometheus_retention_time = "48h",
      disable_hostname = true
    }

